### ISSUE TITLE
Verificar equivalência dos objetos com o arquivo

### ISSUE THREAD

**Issue by ronaldogomes** [ronaldogomes/Genetic-Algorithm-Timetabling#1]
na classe Teste metodo main foram criados os seguintes arrays.
- ArrayList<Curso> cursosEMC = new ArrayList<>();
- ArrayList<Disciplina> DisciplinasEMC = new ArrayList<>();
- ArrayList<Estudante> alunosEMC = new ArrayList<>();
- ArrayList<Professor> professoresEMC = new ArrayList<>();
- ArrayList<Sala> salasEMC = new ArrayList<>();
- ArrayList<TimeSlots> listaTimeSlots = new ArrayList<>();
- ArrayList<TipoSala> tipoSalaEMC = new ArrayList<>();

Testar imprimindo cada lista e verificar se está consistente com o arquivo ag-informacoes.csv

**Comment by ronaldogomes** [comment]
Pacheco check se objetos estão de acordo com o arquivo

**Comment by viniciuspacheco** [comment]
Amanhã vou tentar testar

**Comment by ronaldogomes** [comment]
Encontrei uns erros no carregamento dos objetos professor e estudante. corrigi e coloquei um código para imprimir o ArrayList dos objetos no main (classe Teste) a chamada dos métodos de impressão estão comentados. É só retirar os comentários para imprimir o array de objetos desejado. No exemplo está imprimindo apenas o ArrayList de professores. _**Ressalto que a classe teste vai ser modificada varias vezes no projeto e pode até deixar de existir no futuro.**_

```
//      IMPRIME OS ARRAYS DOS OBJETOS CARREGADOS DO ARQUIVO ag-informacoes.csv      
//      imprimeArrayAlunos(alunosEMC);
//      imprimeArrayCursos(cursosEMC);
//      imprimeArrayDisciplinas(DisciplinasEMC);
        imprimeArrayProfessores(professoresEMC);
//      imprimeArraySalas(salasEMC);
//      imprimeArrayTimesSlots(tipoSalaEMC);
//      imprimeArrayTipoSala(tipoSalaEMC);  
```
